### ISSUE TITLE
Atama reload config not working

### ISSUE THREAD

**Issue by sonofhypnos** [Mishkun/ataman-intellij#10]
When I add a new keybind and trigger the "reload ~/.atamanrc.config File" action, nothing changes. Restarting the IDE works for changing keybinds (although it’s slow).

**Comment by corintho** [comment]
I saw recently that if the file is open in the editor, the reload does not work. But if the file is closed, it works as expected

**Comment by Mishkun** [comment]
@sonofhypnos  Do you save your file after editing it? Intellij is keeping file edits in temporary buffer before saving. Try saving the file by using File -> Save All... before launching config reload command

**Comment by Mishkun** [comment]
I will close this issue because there are no steps to reproduce. Please reopen it If you can provide steps to reproduce
