### ISSUE TITLE
Any plans to introduce repetitive commands?

### ISSUE THREAD

**Issue by Ed-Pavlov** [Mishkun/ataman-intellij#2]
I mean if I set up "Go to next error" using ataman it's still not easy to press, say, Ctrl+E E(error) N(next) several times in a row.
I have no idea is it even possible, because, if I got it right, Ataman works by capturing a keyboard focus to it's "menu".

**Comment by Mishkun** [comment]
It could be possible to implement in two ways:
1) Like in vim one could enter a number before command to repeat it n times. e.g. j is command to move down and 23j is move down 23 times. I could add support for that, but this case is mostly useful for text editing, not for high-level commands like "next error"
2) Or I could add an intellij action to repeat latest ataman command. Then you could bind it for shorcut of your choice to repeat. I think this is a much better solution for your problem

**Comment by Aneeqasif** [comment]
any updates on it?
