### ISSUE TITLE
keyboard reads too slow?

### ISSUE THREAD

**Issue by lexinator** [Mishkun/ataman-intellij#3]
In my very short 5 minutes usage, when i hit `<leader><character 1><character 2>` in quick succession it usually interpreted this as `<leader><character 2>` so some how `<character 1>` was lost.  If the expectation is to hit leader and wait then hit the remaining command characters then I wouldn't be able to use this plugin.  However it's very possible that I have some configuration causing it to be slow, so any pointers here to aid in debugging how the character was lost.

I do like the idea for this plugin rather than customizing all my own.  I've learned about this repository via https://github.com/JetBrains/ideavim/discussions/345#discussioncomment-1429448.

**Comment by Dakes** [comment]
@Mishkun  Hey, I appreciate the latest update. Did you change something regarding this?
The small delay also always bothered me a bit. But in the current version it seems to be gone. It feels very responsive now.

**Comment by Mishkun** [comment]
@Dakes I did nothing specific for this in the latest updates. Maybe updating dependencies and rewriting depricated methods usages hepled. Or maybe it is just a fluke, who knows?

Glad you enjoyed my work! I'm still open for ideas on this issue though

**Comment by Mishkun** [comment]
@Dakes @lexinator I think I know what happened here and why 1.3.0 feels more responsive. I changed the keystroke detection from KEY_RELEASED to KEY_PRESSED. For those who are heavy typist it may feel like a significant change in responsiveness. Please tell me if I'm wrong.

**Comment by Dakes** [comment]
I just tried the old version again and the problem I was having was when quickly typing `<leader>+c` to open the code menu c would get registered as a normal command, before the menu could open. I guess that happened, when I was rolling the key strokes. So that change solved this issue by registering the keys even when I have multiple pressed at the same time.  👍

**Comment by Mishkun** [comment]
Nice, I'll close the issue then.

Note to future self: use down key presses when dealing with physical keyboards instead of up key presses that I'm used to when developing android apps
