### ISSUE TITLE
Some chars can not be bound

### ISSUE THREAD

**Issue by megawubs** [Mishkun/ataman-intellij#9]
First off, thanks for this awesome plugin! It has helped me embrace ideaVim completely.

As I'm going through setting up my bindings I found out that binding some special chars does not work. 

Given the following config:

```HOCON
bindings {
  "." {
    description: "+Collapse"
    bindings {
      "/" {actionId: CollapseAllRegions, description: Collapse All Regions}
      "?" {actionId: ExpandAllRegions, description: Expand All Regions}
      "." {actionId: CollapseRegion, description: Collapse region}
      ">" {actionId: ExpandRegion, description: Expand Region}
    }
  }
}
```
Only te `.` and `/` bindings work. `>` and `?` are listed as a child from `.` but are not beging executed. 

After some testing it seems that all special chars that require me to use the shift key (except capital letters) do not work.

I've tested `~`, `|`, `:` and `>` But I have a hunch there are more that do not work.

**Comment by Mishkun** [comment]
Hi! Thanks for your feedback. Unfortunately, implementation of keycode-to-char-mapping is a bit tricky in Swing when shifting is involved.

Right now it is done by simply calling `char.isUpperCase()` here https://github.com/Mishkun/ataman-intellij/blob/master/src/main/kotlin/io/github/mishkun/ataman/AtamanConfig.kt#L74

Maybe we can provide a proper qwerty-mapping for this to work. Although it can mess with alternative keyboard layouts. Or a special symbol for defining modifier keys
